<a href="https://colab.research.google.com/github/prashantghevde1/Pytorch/blob/main/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import torch

In [2]:
list = [1,2,3,4,5]
list

[1, 2, 3, 4, 5]

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.77194369, 0.33272908, 0.90248477, 0.56288396],
       [0.76754321, 0.33614451, 0.12285222, 0.82354956],
       [0.201251  , 0.72823708, 0.41162209, 0.08128913]])

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.1963, -1.5142, -0.5610,  1.3156],
        [-0.5672, -1.8221,  0.7599,  0.6604],
        [-0.6554, -2.0386,  0.0524, -0.1900]])

In [9]:
tensor_1 = torch.tensor(np1)
tensor_1

tensor([[0.7719, 0.3327, 0.9025, 0.5629],
        [0.7675, 0.3361, 0.1229, 0.8235],
        [0.2013, 0.7282, 0.4116, 0.0813]], dtype=torch.float64)

In [10]:
my_torch = torch.arange(12)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
my_torch5 = my_torch.reshape(-1,3)
my_torch5

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [22]:
my_torch5[:,::]

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [26]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])
tensor_c = tensor_a + tensor_b
tensor_c

tensor([ 6,  8, 10, 12])

In [27]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [28]:
import torch.nn as nn
import torch.nn.functional as F

In [46]:
class Model(nn.Module):
  def __init__(self, in_features=4, h1=8, h2=9, out_features=3):
    super().__init__() # Call the parent class constructor
    self.connect1 = nn.Linear(in_features, h1)
    self.connect2 = nn.Linear(h1, h2)
    self.connect3 = nn.Linear(h2, out_features)

  def forward(self, x):
    x = F.relu(self.connect1(x))
    x = F.relu(self.connect2(x))
    x = self.connect3(x)
    return x

In [51]:
#import torch
#torch.manual_seed(42)
my_model = my_class()